[package]
name = "demo_egor_secs_particles"
version = "0.1.0"
edition = "2024"

[features]
webgl = ["egor/webgl"]

[dependencies]
egor = { path = "../../" }
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
secs = { git = "https://github.com/wick3dr0se/secs", version = "0.1.0" }
